---
- hosts: "{{ my_hosts }}"
  remote_user: root
  sudo: yes

  tasks:
  - name: Install common packages for Ubuntu servers
    apt: name={{ item }} state=present
	with_items:
	  - unzip
	  - git-core
	  - ack-grep
	  - vim
	  - tmux
	  - curl
	  - python-software-properties
